version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Dependencies
          command: |
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            else
              echo "No requirements.txt file found. Skipping dependency installation."
            fi
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Run Tests
          command: pytest

  build:
    docker:
      - image: python:3.8
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Check Docker Version
          command: docker --version
      - run:
          name: Display PATH
          command: echo "C:\Program Files\Docker\Docker\resources\bin" | Out-File -Append -FilePath $PROFILE -Encoding UTF8
      - run:
          name: Install Dependencies
          command: |
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            else
              echo "No requirements.txt file found. Skipping dependency installation."
            fi
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Build Docker Image
          command: docker build -t mayukyadav/test_driven_development:tdd_code .
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "Meridian#123" | docker login -u "mayukyadav" --password-stdin
            docker push mayukyadav/test_driven_development:tdd_code

workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          requires:
            - test