version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt file found. Skipping dependency installation."
          fi

      - name: Install pytest
        run: pip install pytest

      - name: Run Tests
        run: pytest

  build:
    docker:
      - image: python:3.8
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Docker Version
        run: docker --version

      - name: Display PATH
        run: echo 'export PATH=$PATH:/path/to/your/docker/bin' >> $HOME/.bashrc

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt file found. Skipping dependency installation."
          fi

      - name: Install pytest
        run: pip install pytest

      - name: Build Docker Image
        run: docker build -t mayukyadav/test_driven_development:tdd_code .

      - name: Push Docker Image to Docker Hub
        run: |
          echo 'Meridian#123' | docker login -u 'mayukyadav' --password-stdin
          docker push mayukyadav/test_driven_development:tdd_code

workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          requires:
            - test
