version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            else
              echo "No requirements.txt file found. Skipping dependency installation."
            fi
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Run Tests
          command: pytest

workflows:
  version: 2
  test:
    jobs:
      - test
