 
version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt  # If you have any dependencies
      - run:
          name: Run Tests
          command: pytest

workflows:
  version: 2
  test:
    jobs:
      - test
