version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo pip install pytest

      - run:
          name: Run tests
          command: |
            pytest

      - run:
          name: Build Docker image
          command: |
            docker build -t mayukyadav/tdd_code:latest .

      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "Meridian#123" | docker login -u "mayukyadav" --password-stdin
            docker push mayukyadav/tdd_code:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main  # Adjust to your main branch name
