version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - setup_remote_docker
      - checkout             #
      - run:
          name: Install Dependencies
          command: |
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            else
              echo "No requirements.txt file found. Skipping dependency installation."
            fi
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Run Tests
          command: pytest

  build:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Check Docker Version
          command: docker --version
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      - run:
          name: Display PATH
          command: echo $PATH
      - run:
          name: Install Dependencies
          command: |
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            else
              echo "No requirements.txt file found. Skipping dependency installation."
            fi
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Build Docker Image
          command: docker build -t mayukyadav/test_driven_development:tdd_code .
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "Meridian#123" | docker login -u "mayukyadav" --password-stdin
            docker push mayukyadav/test_driven_development:tdd_code

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test